### ISSUE TITLE
Infinite loop in _bpe when tokenising ","

### ISSUE THREAD

**Issue by lbeurerkellner** [alisonjf/gpt3-tokenizer#1]
Thanks for this awesome implementation :) Experimenting, I just found that the following input string causes an infinite loop in the `_bpe` function:

```
import gpt3_tokenizer

s = '","'
ids = gpt3_tokenizer.encode(s)
print(gpt3_tokenizer.decode(ids))
print(gpt3_tokenizer.decode(ids) == s)
```

It seems the joining of subtokens via `,` in the code, conflicts with actual `,` characters appearing as part of tokens. I tried to switch to tuples instead of comma separated lists of tokens for `bpe_ranks`, but it does not seem to do the trick.

I would really appreciate some help in fixing it. Thanks a lot in advance.

**Comment by lbeurerkellner** [comment]
I think I found a way, see #2 .

**Comment by alisonjf** [comment]
@lbeurerkellner As I said in the PR, the fix is solid! Thanks again for your contribution!
