### ISSUE TITLE
Unicode-decode error while importing the library in anaconda jupyter notebook 

### ISSUE THREAD

**Issue by satvik27git** [alisonjf/gpt3-tokenizer#3]
Hi I am trying to import this library in my jupyter notebook 
import gpt3_tokenizer
and getting this error:
UnicodeDecodeError                        Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_31800\2840982467.py in <module>
----> 1 import gpt3_tokenizer
      2 
      3 #a_string = "That's my beautiful and sweet string"
      4 #tokens_count = gpt3_tokenizer.count_tokens(a_string) # outputs 7
      5 #tokens_count

~\Anaconda3\lib\site-packages\gpt3_tokenizer\__init__.py in <module>
----> 1 from gpt3_tokenizer._entry import count_tokens, decode, encode
      2 
      3 __all__ = [
      4     "encode",
      5     "decode",

~\Anaconda3\lib\site-packages\gpt3_tokenizer\_entry.py in <module>
      8                                        _init_encoder)
      9 
---> 10 _bpe_merges = _get_bpe_merges()
     11 _bpe_ranks = _dict_zip(_bpe_merges, range(0, len(_bpe_merges)))
     12 _REGEX_PATTERN = r"'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+"

~\Anaconda3\lib\site-packages\gpt3_tokenizer\_functions.py in _get_bpe_merges()
     18 def _get_bpe_merges():
     19     with open(os.path.join(os.path.dirname(__file__), "data/vocab.bpe"), "r") as f:
---> 20         bpe_lines = f.readlines()
     21         sliced = bpe_lines[1:len(bpe_lines)-1]
     22         bpe_merges = [regex.split(r"(\s+)", s) for s in sliced]

~\Anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

**UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1415: character maps to <undefined>**

Python version is above 3 , windows 11

**Comment by devanghingu** [comment]
Facing same issue with `windows-11` with `python 3.8`

**Comment by alisonjf** [comment]
@devanghingu @satvik27git fix was released, just use the `0.1.5` version of the lib: https://pypi.org/project/gpt3_tokenizer/
